### ISSUE TITLE
third test claims to expect three properties but only expects two

### ISSUE THREAD

**Issue by jonopens** [learn-co-curriculum/js-object-oriented-constructor-functions-lab#1]
To reproduce:
- clone down lab
- run learn command in terminal
- read html output of third test
- open indexTest.js in test/
- note lines 27, 29, 30 refer two only two total attributes for a PickupLocation object

**Comment by hansenjl** [comment]
Still an issue

**Comment by Sidhe-is-me** [comment]
Still an issue.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
Thanks for your contribution 💙
