### ISSUE TITLE
change wording in indexTest.js

### ISSUE THREAD

**Issue by halfields** [learn-co-curriculum/js-object-oriented-constructor-functions-lab#2]
Line 26 of indexTest.js reads in part:"should create a new PickupLocation with three properties" 
That should be changed to:"should create a new PickupLocation with two properties"

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
Thanks for your contribution 💙
