### ISSUE TITLE
PickupLocation constructor test number of properties

### ISSUE THREAD

**Issue by zoebisch** [learn-co-curriculum/js-object-oriented-constructor-functions-lab#3]
Test references "should create a new PickupLocation with three properties".  There are only two created and passed into the constructor. 

suggest changing "three" to "two".

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
Thanks for your contribution 💙
